### ISSUE TITLE
gpt-sovits-40aecd__api对应NAS 文件系统，无法通过浏览器打开。gpt-sovits-40aecd的可以

### ISSUE THREAD

**Issue by Downupanddownup** [devsapp/fc-gpt-sovits#2]
![image](https://github.com/devsapp/fc-gpt-sovits/assets/12596230/22cd16b7-6d74-4e35-a285-b26901ad115b)
项目启动失败，失败原因 Error: The function either cannot be started or exited. Function instance exited unexpectedly(code 128, message:key has been revoked) with start command './server '.。
建议您重新部署 NAS 浏览器（函数计算 FC 应用）
挺奇怪的，webui的那个函数绑定的文件系统能够正常访问，但是api的就访问不了。问了阿里云的技术，也没什么有效回复。不知道你这边有什么头绪吗？

**Comment by zxypro1** [comment]
可以在FC的控制台上把filemgr开头的应用都删掉，然后重新挂个浏览器试试

**Comment by Downupanddownup** [comment]
> 可以在FC的控制台上把filemgr开头的应用都删掉，然后重新挂个浏览器试试

这个我试过了，之前是两个都不行，后台webui的可以了，但是api的还是不行。后来我想了下会不会是api没初始化过的原因，用触发器下的网址访问了下接口，启动了实例，能登录实例，用linux指令查看目录。不过，去NAS文件系统下，重建一个新的文件FC应用，用浏览器访问，还是不行。等明天再去FC群里问问看吧。

**Comment by zxypro1** [comment]
正常来说webui和api应用用的是同一个nas，只是文件夹名不一样。你是怎么看api的nas的呢

**Comment by Downupanddownup** [comment]
![image](https://github.com/devsapp/fc-gpt-sovits/assets/12596230/fa655b24-0f3e-442a-8d49-955306c089ce)
![image](https://github.com/devsapp/fc-gpt-sovits/assets/12596230/a7d71282-15f4-4b5c-abd7-412554653a89)
![image](https://github.com/devsapp/fc-gpt-sovits/assets/12596230/9a8a0329-c0bf-4d3b-965c-311168f2a537)
![image](https://github.com/devsapp/fc-gpt-sovits/assets/12596230/200699af-b00f-49e0-bbde-7f0690551055)

![image](https://github.com/devsapp/fc-gpt-sovits/assets/12596230/63365036-a9d7-4484-bffe-54371bbd331d)

**Comment by Downupanddownup** [comment]
我用你的那个一键部署链接创建应用之后，出现了两个文件系统，难道是，部署过程中，出错了？

**Comment by Downupanddownup** [comment]
成功了！我把fc-gpt-sovits应用删了之后重新部署，两个函数都指向同一个nas了，终于可以使用在线服务了。不过api函数的公网ip是不是临时的，30天之后，是不是会被回收？
![image](https://github.com/devsapp/fc-gpt-sovits/assets/12596230/c303c4bb-7777-4280-8724-59b214593fd1)

**Comment by zxypro1** [comment]
可以绑个自定义域名

**Comment by Downupanddownup** [comment]
好的，多谢！
