### ISSUE TITLE
{"RequestId":"1-6672aaa1-156f9d96-18e1aa793595","Code":"ResourceThrottled","Message":"Reserve resource exceeded limit"}

### ISSUE THREAD

**Issue by Downupanddownup** [devsapp/fc-gpt-sovits#3]
在访问阿里云的FC的webui服务的时候，时不时会遇到这个错误，好像是资源不够了，时好时坏。不知道你们是不是会频繁遇到这个问题？
![image](https://github.com/devsapp/fc-gpt-sovits/assets/12596230/ed802e21-725c-429f-8290-ffff43146aa1)

**Comment by zxypro1** [comment]
对，FC是纯弹性使用，有时候会遇到资源争抢。可以重试或者做预留，预留的成本会高一些

**Comment by Downupanddownup** [comment]
ok
